#_______Description_____

#https://projecteuler.net/problem=45
#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#Triangle
# 
#Tn=n(n+1)/2
# 
#1, 3, 6, 10, 15, ...
#Pentagonal
# 
#Pn=n(3n−1)/2
# 
#1, 5, 12, 22, 35, ...
#Hexagonal
# 
#Hn=n(2n−1)
# 
#1, 6, 15, 28, 45, ...
#It can be verified that T285 = P165 = H143 = 40755.
#Find the next triangle number that is also pentagonal and hexagonal.
##_______end_description_____:

import time
start_time = time.time()
penta,hexa=set(),set()
 
def find_numbers(n): #calculate triangle,penta,hexa
    t=int((n*(n+1))/2)
    p=int((n*((3*n)-1))/2)
    h=int(n*((2*n)-1))
    penta.add(p);hexa.add(h)
    return t
 
n=285
while True:
    n+=1;t=find_numbers(n) 
    if t in penta and t in hexa: #check if t in hexa,penta set created
        print(t);break
 
end_time=time.time()-start_time
print(end_time)
